# Generated by Django 3.2.12 on 2022-06-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0021_auto_20220602_2203'),
        ('payments', '0002_payment_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='essentials.accounttype'),
        ),
    ]
