# Generated by Django 3.2.12 on 2022-06-13 18:18

from django.db import migrations, models
import easyaccounts.storage_backends
import payments.utils


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentandimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentimage',
            name='image',
            field=models.ImageField(storage=easyaccounts.storage_backends.PrivateMediaStorage(), upload_to=payments.utils.get_image_upload_path),
        ),
    ]
