# Generated by Django 3.2.12 on 2022-06-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='detail',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
