version: '3'
services:
  backend:
    restart: always
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/backend
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=easy_db
      - POSTGRES_PASSWORD=Pakistan6564!
      - POSTGRES_USER=easyaccounts
    volumes:
      - ./data/db:/var/lib/postgresql/data
