# Generated by Django 3.2.8 on 2021-10-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAccount',
            fields=[
                ('id_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='essentials.id')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('essentials.id',),
        ),
        migrations.CreateModel(
            name='ExpenseDetail',
            fields=[
                ('id_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='essentials.id')),
                ('date', models.DateField(auto_now_add=True)),
                ('detail', models.TextField(max_length=1000)),
                ('amount', models.FloatField()),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.accounttype')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenseaccount')),
            ],
            bases=('essentials.id',),
        ),
    ]
