# Generated by Django 3.2.8 on 2021-10-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensedetail',
            options={'ordering': ['date']},
        ),
    ]
