# Generated by Django 3.2.8 on 2021-10-19 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensedetail_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedetail',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
