# Generated by Django 3.2.12 on 2022-04-17 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0005_expenseaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='expensedetail',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expensedetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
