# Generated by Django 3.2.12 on 2022-06-02 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20220417_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensedetail',
            name='branch',
        ),
        migrations.AlterField(
            model_name='expensedetail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
