# Generated by Django 3.2.12 on 2022-06-02 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20220602_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedetail',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
