# Generated by Django 3.2.12 on 2022-06-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_expensedetail_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedetail',
            name='serial',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
