# Generated by Django 3.2.12 on 2022-06-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_expensedetail_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseaccount',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('maintenance', 'Maintenance'), ('salary', 'Salary'), ('transportation', 'Transportation'), ('administrative', 'Administrative'), ('marketing', 'Marketing'), ('refreshments', 'Refreshments'), ('special', 'Special'), ('commission', 'Commission'), ('printing', 'Printing'), ('legal', 'Legal'), ('communication', 'Communication'), ('taxation', 'Taxation'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=14),
        ),
    ]
