# Generated by Django 3.2.12 on 2022-06-28 22:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_alter_userbranchrelation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('status', models.CharField(choices=[('P', 'Purchased'), ('S', 'Sold')], max_length=15)),
                ('type', models.CharField(choices=[('property', 'Property'), ('equipment', 'Equipment'), ('investment', 'Investment'), ('vehicle', 'Vehicle')], max_length=15)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='authentication.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
