# Generated by Django 3.2.12 on 2022-06-29 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sold_value',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
    ]
