# Generated by Django 3.2.12 on 2022-06-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_sold_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sold_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
