# Generated by Django 3.2.12 on 2022-03-24 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('essentials', '0012_auto_20220319_2025'),
        ('authentication', '0004_alter_userbranchrelation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numerator', models.FloatField()),
                ('denominator', models.FloatField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='authentication.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Baara', 'Baara'), ('Standard', 'Standard')], max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawproduct', to='authentication.branch')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('manual_invoice_serial', models.PositiveBigIntegerField()),
                ('nature', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawtransaction', to='authentication.branch')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawTransactionLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.PositiveBigIntegerField()),
                ('issued', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawtransactionlot', to='authentication.branch')),
                ('raw_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawtransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawProductOpeningStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_stock', models.FloatField(default=0.0)),
                ('opening_stock_rate', models.FloatField()),
                ('gazaana', models.FloatField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawproductopeningstock', to='authentication.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawLotDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('actual_gazaana', models.FloatField()),
                ('expected_gazaana', models.FloatField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawlotdetails', to='authentication.branch')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rawtransactions.formula')),
                ('lot_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawtransactionlot')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essentials.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
