# Generated by Django 3.2.12 on 2022-03-27 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userbranchrelation_role'),
        ('essentials', '0012_auto_20220319_2025'),
        ('rawtransactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawLotDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('actual_gazaana', models.FloatField()),
                ('expected_gazaana', models.FloatField()),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('nature', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='C', max_length=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawlotdetail', to='authentication.branch')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rawtransactions.formula')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='rawtransaction',
            name='nature',
        ),
        migrations.AddField(
            model_name='rawtransactionlot',
            name='raw_product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rawtransactions.rawproduct'),
        ),
        migrations.DeleteModel(
            name='RawLotDetails',
        ),
        migrations.AddField(
            model_name='rawlotdetail',
            name='lot_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawtransactionlot'),
        ),
        migrations.AddField(
            model_name='rawlotdetail',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='essentials.warehouse'),
        ),
    ]
