# Generated by Django 3.2.12 on 2022-03-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0002_auto_20220327_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtransactionlot',
            name='raw_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rawtransactions.rawproduct'),
        ),
    ]
