# Generated by Django 3.2.12 on 2022-03-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userbranchrelation_role'),
        ('essentials', '0012_auto_20220319_2025'),
        ('rawtransactions', '0003_alter_rawtransactionlot_raw_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawproduct',
            unique_together={('person', 'name', 'branch')},
        ),
    ]
