# Generated by Django 3.2.12 on 2022-03-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userbranchrelation_role'),
        ('essentials', '0012_auto_20220319_2025'),
        ('rawtransactions', '0004_alter_rawproduct_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawproduct',
            unique_together={('person', 'name', 'branch', 'type')},
        ),
    ]
