# Generated by Django 3.2.12 on 2022-03-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0006_auto_20220330_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawreturn',
            old_name='bill_num',
            new_name='bill_number',
        ),
    ]
