# Generated by Django 3.2.12 on 2022-03-30 12:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rawtransactions.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0012_auto_20220319_2025'),
        ('rawtransactions', '0007_rename_bill_num_rawreturn_bill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDebit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manual_invoice_serial', models.PositiveBigIntegerField()),
                ('bill_number', models.PositiveBigIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('debit_type', models.CharField(choices=[('Sale', 'Sale'), ('Return', 'Return')], max_length=10)),
            ],
            bases=(models.Model, rawtransactions.models.NextSerial),
        ),
        migrations.CreateModel(
            name='RawDebitLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawDebitLotDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('actual_gazaana', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('expected_gazaana', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='rawreturn',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='rawreturn',
            name='person',
        ),
        migrations.RemoveField(
            model_name='rawreturnlot',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='rawreturnlot',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='rawreturnlot',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='rawreturnlotdetail',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='rawreturnlotdetail',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='rawreturnlotdetail',
            name='return_lot',
        ),
        migrations.RemoveField(
            model_name='rawreturnlotdetail',
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='essentials.person'),
        ),
    ]
