# Generated by Django 3.2.12 on 2022-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0011_auto_20220331_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdebitlotdetail',
            name='nature',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='rawdebit',
            name='debit_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Return', 'Return'), ('Transfer', 'Transfer')], max_length=10),
        ),
    ]
