# Generated by Django 3.2.12 on 2022-03-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0012_auto_20220319_2025'),
        ('rawtransactions', '0012_auto_20220331_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdebit',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='essentials.person'),
        ),
    ]
