# Generated by Django 3.2.12 on 2022-04-15 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawtransactions', '0013_alter_rawdebit_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdebit',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rawdebit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rawtransaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RawProductOpeningStock',
        ),
    ]
