# Generated by Django 3.2.12 on 2022-06-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0021_auto_20220602_2203'),
        ('rawtransactions', '0015_auto_20220602_1244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawdebit',
            unique_together={('manual_invoice_serial', 'debit_type')},
        ),
        migrations.AlterUniqueTogether(
            name='rawproduct',
            unique_together={('person', 'name', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='rawtransaction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rawdebit',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='rawproduct',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='rawtransaction',
            name='branch',
        ),
    ]
