# Generated by Django 3.2.12 on 2022-06-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0016_auto_20220604_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdebit',
            old_name='bill_number',
            new_name='serial',
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='serial',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
