# Generated by Django 3.2.12 on 2022-06-16 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0017_auto_20220605_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtransaction',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
