# Generated by Django 3.2.13 on 2023-05-24 02:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0020_auto_20220620_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdebitlotdetail',
            name='rate_gazaana',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawlotdetail',
            name='rate_gazaana',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(1.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawdebitlotdetail',
            name='formula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rawtransactions.formula'),
        ),
        migrations.AlterField(
            model_name='rawlotdetail',
            name='formula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rawtransactions.formula'),
        ),
    ]
