# Generated by Django 3.2.12 on 2022-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0021_auto_20220813_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawsaleandreturn',
            name='transaction_type',
            field=models.CharField(choices=[('RINV', 'Raw Sale'), ('RMWC', 'Return Customer'), ('RMWS', 'Return Supplier')], max_length=10),
        ),
    ]
