# Generated by Django 3.2.13 on 2023-05-27 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_userbranchrelation_role'),
        ('rawtransactions', '0022_auto_20230527_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdebit',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.branch'),
        ),
    ]
