# Generated by Django 3.2.13 on 2023-05-31 02:21

import core.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_userbranchrelation_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('essentials', '0029_auto_20220718_1511'),
        ('rawtransactions', '0023_rawdebit_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now)),
                ('serial', models.PositiveBigIntegerField()),
                ('manual_serial', models.PositiveBigIntegerField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.branch')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rawtransfer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.NextSerial, models.Model),
        ),
        migrations.CreateModel(
            name='RawTransferLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='rawdebitlotdetail',
            name='nature',
        ),
        migrations.AddField(
            model_name='rawdebit',
            name='manual_serial',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawdebitlot',
            name='detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='manual_serial',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransactionlot',
            name='detail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rawtransactionlot',
            name='dying_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rawtransactionlot',
            name='warehouse_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='RawTransferLotDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('actual_gazaana', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('expected_gazaana', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('raw_transfer_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawtransferlot')),
                ('transferring_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferring_warehouse', to='essentials.warehouse')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='essentials.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='rawtransferlot',
            name='lot_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawtransactionlot'),
        ),
        migrations.AddField(
            model_name='rawtransferlot',
            name='raw_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawtransfer'),
        ),
    ]
