# Generated by Django 3.2.12 on 2022-08-14 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0023_auto_20220814_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpurchaselotdetail',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='rawsaleandreturnlotdetail',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='rawstocktransferlotdetail',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
    ]
