# Generated by Django 3.2.13 on 2023-05-31 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0024_auto_20230531_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawtransferlotdetail',
            name='rate',
        ),
    ]
