# Generated by Django 3.2.12 on 2022-08-15 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawtransactions', '0024_auto_20220814_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawstocktransfer',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rawstocktransfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
