# Generated by Django 3.2.13 on 2023-06-08 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rawtransactions", "0025_remove_rawtransferlotdetail_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdebitlot",
            name="raw_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rawtransactions.rawproduct",
            ),
        ),
        migrations.AddField(
            model_name="rawtransferlot",
            name="raw_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rawtransactions.rawproduct",
            ),
        ),
        migrations.RemoveField(
            model_name="rawdebitlot",
            name="lot_number",
        ),
        migrations.RemoveField(
            model_name="rawtransferlot",
            name="lot_number",
        ),
        migrations.AddField(
            model_name="rawdebitlot",
            name="lot_number",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="rawtransferlot",
            name="lot_number",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
