# Generated by Django 3.2.13 on 2023-06-10 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0026_auto_20230608_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdebit',
            name='debit_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase_return', 'Purchase Return'), ('sale_return', 'Sale Return')], max_length=15),
        ),
        migrations.AlterField(
            model_name='rawdebitlot',
            name='bill_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='rawtransactions.rawdebit'),
        ),
        migrations.AlterField(
            model_name='rawdebitlotdetail',
            name='return_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_detail', to='rawtransactions.rawdebitlot'),
        ),
        migrations.AlterField(
            model_name='rawlotdetail',
            name='lot_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_detail', to='rawtransactions.rawtransactionlot'),
        ),
        migrations.AlterField(
            model_name='rawtransactionlot',
            name='raw_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='rawtransactions.rawtransaction'),
        ),
        migrations.AlterField(
            model_name='rawtransferlot',
            name='raw_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='rawtransactions.rawtransfer'),
        ),
        migrations.AlterField(
            model_name='rawtransferlotdetail',
            name='raw_transfer_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_detail', to='rawtransactions.rawtransferlot'),
        ),
    ]
