# Generated by Django 3.2.13 on 2023-07-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_alter_userbranchrelation_role"),
        ("rawtransactions", "0027_auto_20230610_2234"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdebitlot",
            name="product_glue",
            field=models.CharField(
                choices=[("LG", "Low Glue"), ("HG", "High Glue"), ("CFG", "Centrifugal")],
                default="LG",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rawdebitlot",
            name="product_type",
            field=models.CharField(
                choices=[("Baara", "Baara"), ("Standard", "Standard")],
                default="Baara",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rawproduct",
            name="branch",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.branch",
            ),
        ),
        migrations.AddField(
            model_name="rawtransactionlot",
            name="product_glue",
            field=models.CharField(
                choices=[("LG", "Low Glue"), ("HG", "High Glue"), ("CFG", "Centrifugal")],
                default="LG",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rawtransactionlot",
            name="product_type",
            field=models.CharField(
                choices=[("Baara", "Baara"), ("Standard", "Standard")],
                default="Baara",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rawtransferlot",
            name="product_glue",
            field=models.CharField(
                choices=[("LG", "Low Glue"), ("HG", "High Glue"), ("CFG", "Centrifugal")],
                default="LG",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rawtransferlot",
            name="product_type",
            field=models.CharField(
                choices=[("Baara", "Baara"), ("Standard", "Standard")],
                default="Baara",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="rawproduct",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="rawproduct",
            name="person",
        ),
        migrations.RemoveField(
            model_name="rawproduct",
            name="type",
        ),
    ]
