# Generated by Django 3.2.12 on 2022-03-04 16:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('nature', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
                ('discount', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('draft', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('maal_wapsi', 'Maal Wapsi'), ('paid', 'Paid'), ('purchase', 'Purchase'), ('credit', 'Credit')], max_length=10)),
                ('serial', models.BigIntegerField(unique=True)),
                ('detail', models.CharField(max_length=1000, null=True)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('manual_invoice_serial', models.BigIntegerField()),
                ('manual_serial_type', models.CharField(max_length=3)),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.accounttype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.person')),
            ],
            options={
                'ordering': ['-date', '-serial'],
                'unique_together': {('manual_invoice_serial', 'manual_serial_type')},
            },
        ),
        migrations.CreateModel(
            name='TransferEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('yards_per_piece', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_warehouse', to='essentials.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.product')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_warehouse', to='essentials.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('yards_per_piece', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_detail', to='transactions.transaction')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='CancelledInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manual_invoice_serial', models.BigIntegerField(unique=True)),
                ('manual_serial_type', models.CharField(max_length=3)),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'unique_together': {('manual_invoice_serial', 'manual_serial_type')},
            },
        ),
    ]
