# Generated by Django 3.2.8 on 2021-10-12 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.id')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
                ('discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.warehouse')),
            ],
            bases=('transactions.id',),
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.id')),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.product')),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            bases=('transactions.id',),
        ),
    ]
