# Generated by Django 3.2.8 on 2021-10-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20211018_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='nature',
        ),
    ]
