# Generated by Django 3.2.12 on 2022-03-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('transactions', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledinvoice',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelledinvoice', to='authentication.branch'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='authentication.branch'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactiondetail', to='authentication.branch'),
        ),
        migrations.AddField(
            model_name='transferentry',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferentry', to='authentication.branch'),
        ),
    ]
