# Generated by Django 3.2.12 on 2022-03-09 15:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_branch_options'),
        ('transactions', '0003_auto_20220309_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferentry',
            options={'verbose_name_plural': 'Transfer entries'},
        ),
        migrations.AlterField(
            model_name='cancelledinvoice',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='cancelledinvoice', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='transactiondetail', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='transferentry',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='transferentry', to='authentication.branch'),
        ),
    ]
