# Generated by Django 3.2.8 on 2021-10-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_type_transaction_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_detail', to='transactions.transaction'),
        ),
    ]
