# Generated by Django 3.2.8 on 2021-10-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='paid', max_length=10),
            preserve_default=False,
        ),
    ]
