# Generated by Django 3.2.12 on 2022-03-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_branch_options'),
        ('transactions', '0004_auto_20220309_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledinvoice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelledinvoice', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactiondetail', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='transferentry',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferentry', to='authentication.branch'),
        ),
    ]
