# Generated by Django 3.2.12 on 2022-03-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_branch_options'),
        ('transactions', '0005_auto_20220309_2054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('manual_invoice_serial', 'manual_serial_type', 'branch')},
        ),
    ]
