# Generated by Django 3.2.8 on 2021-10-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('maal_wapsi', 'Maal Wapsi'), ('paid', 'Paid'), ('purchase', 'Purchase'), ('credit', 'Credit')], max_length=10),
        ),
    ]
