# Generated by Django 3.2.8 on 2021-10-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='serial',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
