# Generated by Django 3.2.12 on 2022-03-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_branch_options'),
        ('transactions', '0007_alter_transaction_serial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cancelledinvoice',
            unique_together={('manual_invoice_serial', 'manual_serial_type', 'branch')},
        ),
    ]
