# Generated by Django 3.2.8 on 2021-10-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='serial',
            field=models.IntegerField(unique=True),
        ),
    ]
