# Generated by Django 3.2.8 on 2021-10-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='detail',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
