# Generated by Django 3.2.12 on 2022-03-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_cancelledinvoice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledinvoice',
            name='manual_invoice_serial',
            field=models.BigIntegerField(),
        ),
    ]
