# Generated by Django 3.2.12 on 2022-03-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_cancelledinvoice_manual_invoice_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='requires_action',
            field=models.BooleanField(default=False),
        ),
    ]
