# Generated by Django 3.2.8 on 2021-11-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
        ('transactions', '0009_transaction_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.accounttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
