# Generated by Django 3.2.12 on 2022-03-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0012_auto_20220319_2025'),
        ('transactions', '0010_transaction_requires_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='essentials.product'),
        ),
    ]
