# Generated by Django 3.2.8 on 2022-01-15 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20211110_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='yards_per_piece',
            field=models.FloatField(default=44.0, validators=[django.core.validators.MinValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
