# Generated by Django 3.2.11 on 2022-01-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transactiondetail_yards_per_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='manual_invoice_serial',
            field=models.BigIntegerField(default=213, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='serial',
            field=models.BigIntegerField(unique=True),
        ),
    ]
