# Generated by Django 3.2.12 on 2022-04-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20220410_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='manual_serial_type',
            field=models.CharField(choices=[('INV', 'Sale Invoice'), ('SUP', 'Purchase'), ('MWS', 'Maal Wapsi Supplier'), ('MWC', 'Maal Wapsi Customer')], max_length=3),
        ),
    ]
