# Generated by Django 3.2.11 on 2022-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='manual_invoice_serial',
            field=models.CharField(max_length=255),
        ),
    ]
