# Generated by Django 3.2.12 on 2022-04-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20220415_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferEntry',
        ),
    ]
