# Generated by Django 3.2.11 on 2022-02-05 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_transaction_manual_invoice_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manual_invoice_serial', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='manual_invoice_serial',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
