# Generated by Django 3.2.12 on 2022-04-17 13:14

from django.db import migrations, models
import django.db.models.deletion
import rawtransactions.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userbranchrelation_role'),
        ('essentials', '0017_alter_person_unique_together'),
        ('transactions', '0014_delete_transferentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='serial',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.CreateModel(
            name='CancelStockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manual_invoice_serial', models.PositiveBigIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelstocktransfer', to='authentication.branch')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='essentials.warehouse')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, rawtransactions.models.NextSerial),
        ),
    ]
