# Generated by Django 3.2.11 on 2022-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20220205_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledinvoice',
            name='manual_serial_type',
            field=models.CharField(default='SUP', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='manual_serial_type',
            field=models.CharField(default='SUP', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cancelledinvoice',
            name='manual_invoice_serial',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='manual_invoice_serial',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cancelledinvoice',
            unique_together={('manual_invoice_serial', 'manual_serial_type')},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('manual_invoice_serial', 'manual_serial_type')},
        ),
    ]
