# Generated by Django 3.2.12 on 2022-04-20 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0016_auto_20220418_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledinvoice',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelledinvoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancelstocktransfer',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelstocktransfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
