# Generated by Django 3.2.11 on 2022-02-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20220205_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='manual_invoice_serial',
            field=models.BigIntegerField(),
        ),
    ]
