# Generated by Django 3.2.11 on 2022-02-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_alter_transaction_manual_invoice_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledinvoice',
            name='comment',
            field=models.CharField(default='hello', max_length=500),
            preserve_default=False,
        ),
    ]
