# Generated by Django 3.2.11 on 2022-02-05 18:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0010_alter_person_phone_number'),
        ('transactions', '0018_cancelledinvoice_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yards_per_piece', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_warehouse', to='essentials.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.product')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_warehouse', to='essentials.warehouse')),
            ],
        ),
    ]
