# Generated by Django 3.2.12 on 2022-06-02 07:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_remove_transactiondetail_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransferdetail',
            name='branch',
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='stocktransferdetail',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='stocktransferdetail',
            name='yards_per_piece',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='yards_per_piece',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
    ]
