# Generated by Django 3.2.11 on 2022-02-05 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_transferentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
