# Generated by Django 3.2.12 on 2022-06-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_auto_20220602_1246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('manual_invoice_serial', 'manual_serial_type')},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='branch',
        ),
    ]
