# Generated by Django 3.2.12 on 2022-06-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20220605_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelstocktransfer',
            name='branch',
        ),
    ]
