# Generated by Django 3.2.12 on 2022-06-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_remove_cancelstocktransfer_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelstocktransfer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cancelstocktransfer',
            name='warehouse',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='manual_serial_type',
            new_name='serial_type',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='manual_invoice_serial',
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='CancelledInvoice',
        ),
        migrations.DeleteModel(
            name='CancelStockTransfer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='manual_invoice_serial',
        ),
    ]
