# Generated by Django 3.2.12 on 2022-07-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_auto_20220626_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='manual_serial',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
