# Generated by Django 3.2.12 on 2022-07-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_stocktransfer_manual_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='branch',
        ),
    ]
