# Generated by Django 3.2.13 on 2022-12-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_remove_stocktransfer_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wasooli_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
