# Generated by Django 3.2.13 on 2022-12-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_transaction_wasooli_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
