# Generated by Django 3.2.12 on 2022-03-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userbranchrelation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbranchrelation',
            name='role',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('admin', 'Admin'), ('saleman', 'Saleman'), ('purchaser', 'Purchaser')], default='accountant', max_length=20),
        ),
    ]
