# Generated by Django 3.2.12 on 2022-07-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userbranchrelation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbranchrelation',
            name='role',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('admin', 'Admin'), ('saleman', 'Saleman'), ('purchaser', 'Purchaser'), ('stockist', 'Stockist')], default='accountant', max_length=20),
        ),
    ]
