# Generated by Django 3.2.13 on 2023-06-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userbranchrelation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbranchrelation',
            name='role',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('head_accountant', 'Head Accountant'), ('admin', 'Admin'), ('saleman', 'Saleman'), ('purchaser', 'Purchaser'), ('stockist', 'Stockist'), ('admin_viewer', 'Admin Viewer')], default='accountant', max_length=20),
        ),
    ]
