# Generated by Django 3.2.12 on 2022-03-04 16:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('essentials', '0001_initial'),
        ('transactions', '0001_initial'),
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('detail', models.TextField(blank=True, max_length=1000, null=True)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('nature', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
                ('draft', models.BooleanField(default=False)),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.accounttype')),
                ('external_cheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cheques.externalcheque')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.person')),
                ('personal_cheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cheques.personalcheque')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
