# Generated by Django 3.2.8 on 2021-10-12 20:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='amount',
            field=models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledger',
            name='detail',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
        ),
    ]
