# Generated by Django 3.2.8 on 2021-10-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
