# Generated by Django 3.2.12 on 2022-03-09 15:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_branch_options'),
        ('ledgers', '0002_ledger_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='authentication.branch'),
        ),
    ]
