# Generated by Django 3.2.12 on 2022-03-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_branch_options'),
        ('ledgers', '0003_alter_ledger_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='authentication.branch'),
        ),
    ]
