# Generated by Django 3.2.8 on 2021-10-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
        ('transactions', '0001_initial'),
        ('ledgers', '0003_auto_20211022_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionandledger',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='transactionandledger',
            name='transaction',
        ),
        migrations.AddField(
            model_name='ledger',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.accounttype'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
        ),
        migrations.DeleteModel(
            name='LedgerAndAccountType',
        ),
        migrations.DeleteModel(
            name='TransactionAndLedger',
        ),
    ]
