# Generated by Django 3.2.12 on 2022-03-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0001_initial'),
        ('ledgers', '0004_alter_ledger_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='raw_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawtransaction'),
        ),
    ]
