# Generated by Django 3.2.8 on 2021-10-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0005_auto_20211022_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
