# Generated by Django 3.2.12 on 2022-03-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0008_auto_20220330_1701'),
        ('ledgers', '0006_ledger_raw_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='raw_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawdebit'),
        ),
    ]
