# Generated by Django 3.2.8 on 2021-10-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0006_ledger_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['date']},
        ),
    ]
