# Generated by Django 3.2.8 on 2021-11-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0007_alter_ledger_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-date']},
        ),
    ]
