# Generated by Django 3.2.12 on 2022-04-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0009_ledger_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='draft',
        ),
    ]
