# Generated by Django 3.2.11 on 2022-02-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0004_cheque_person'),
        ('ledgers', '0010_ledger_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_cheque', to='cheques.cheque'),
        ),
    ]
