# Generated by Django 3.2.12 on 2022-06-02 07:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0010_remove_ledger_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
