# Generated by Django 3.2.11 on 2022-02-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0012_rename_issued_to_personalcheque_person'),
        ('ledgers', '0012_auto_20220218_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='personal_cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cheques.personalcheque'),
        ),
    ]
