# Generated by Django 3.2.12 on 2022-06-07 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_remove_cancelstocktransfer_branch'),
        ('ledgers', '0012_ledger_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAndTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledgers.ledger')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
