# Generated by Django 3.2.12 on 2022-06-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_remove_cancelstocktransfer_branch'),
        ('ledgers', '0013_ledgerandtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerandtransaction',
            name='ledger_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transaction', to='ledgers.ledger'),
        ),
        migrations.AlterField(
            model_name='ledgerandtransaction',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
        ),
    ]
