# Generated by Django 3.2.12 on 2022-06-07 15:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_remove_cancelstocktransfer_branch'),
        ('rawtransactions', '0017_auto_20220605_1254'),
        ('cheques', '0012_auto_20220605_2035'),
        ('ledgers', '0014_auto_20220607_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerandtransaction',
            name='ledger_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transaction', to='ledgers.ledger'),
        ),
        migrations.AlterField(
            model_name='ledgerandtransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
        ),
        migrations.CreateModel(
            name='LedgerAndRawTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_raw_transaction', to='ledgers.ledger')),
                ('raw_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawtransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerAndRawDebit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_raw_debit', to='ledgers.ledger')),
                ('raw_debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawdebit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerAndPersonalCheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_personal_cheque', to='ledgers.ledger')),
                ('personal_cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.personalcheque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerAndExternalCheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.externalcheque')),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_external_cheque', to='ledgers.ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
