# Generated by Django 3.2.12 on 2022-06-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0015_auto_20220607_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='external_cheque',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='personal_cheque',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='raw_debit',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='raw_transaction',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='transaction',
        ),
    ]
