# Generated by Django 3.2.12 on 2022-06-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0016_auto_20220607_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerandexternalcheque',
            name='ledger_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_external_cheque', to='ledgers.ledger'),
        ),
        migrations.AlterField(
            model_name='ledgerandpersonalcheque',
            name='ledger_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_personal_cheque', to='ledgers.ledger'),
        ),
        migrations.AlterField(
            model_name='ledgerandrawdebit',
            name='ledger_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_raw_debit', to='ledgers.ledger'),
        ),
        migrations.AlterField(
            model_name='ledgerandrawtransaction',
            name='ledger_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_raw_transaction', to='ledgers.ledger'),
        ),
        migrations.AlterField(
            model_name='ledgerandtransaction',
            name='ledger_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transaction', to='ledgers.ledger'),
        ),
    ]
