# Generated by Django 3.2.12 on 2022-06-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0017_auto_20220607_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='detail',
        ),
    ]
