# Generated by Django 3.2.12 on 2022-06-12 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_account_type'),
        ('ledgers', '0018_remove_ledger_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAndPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_payment', to='ledgers.ledger')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_ledger', to='payments.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
