# Generated by Django 3.2.12 on 2022-06-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0019_ledgerandpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='branch',
        ),
    ]
