# Generated by Django 3.2.12 on 2022-06-15 20:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_remove_cancelstocktransfer_branch'),
        ('payments', '0006_alter_paymentimage_image'),
        ('ledgers', '0020_remove_ledger_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerandtransaction',
            name='ledger_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledgers.ledger'),
        ),
        migrations.CreateModel(
            name='LedgerAndTransactionAndPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transaction_payment', to='ledgers.ledger')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_ledger_transaction', to='payments.payment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_ledger_payment', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
