# Generated by Django 3.2.12 on 2022-06-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0021_auto_20220615_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerandtransaction',
            name='ledger_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transaction', to='ledgers.ledger'),
        ),
    ]
