# Generated by Django 3.2.12 on 2022-06-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_remove_cancelstocktransfer_branch'),
        ('ledgers', '0022_alter_ledgerandtransaction_ledger_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerandtransactionandpayment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_ledger_payment', to='transactions.transaction'),
        ),
    ]
