# Generated by Django 3.2.12 on 2022-06-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0024_alter_ledgerandtransactionandpayment_ledger_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LedgerAndTransactionAndPayment',
        ),
    ]
