# Generated by Django 3.2.12 on 2022-06-30 20:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0025_delete_ledgerandtransactionandpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAndDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=1000)),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_detail', to='ledgers.ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
