# Generated by Django 3.2.12 on 2022-08-13 18:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledgers", "0026_ledgeranddetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerAndRawPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LedgerAndRawSaleAndReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_raw_sale_and_return",
                        to="ledgers.ledger",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        # migrations.RemoveField(
        #     model_name='ledgerandrawtransaction',
        #     name='ledger_entry',
        # ),
        # migrations.RemoveField(
        #     model_name='ledgerandrawtransaction',
        #     name='raw_transaction',
        # ),
        migrations.DeleteModel(
            name="LedgerAndRawDebit",
        ),
        migrations.DeleteModel(
            name="LedgerAndRawTransaction",
        ),
    ]
