# Generated by Django 3.2.12 on 2022-08-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawtransactions', '0021_auto_20220813_1816'),
        ('ledgers', '0027_auto_20220813_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerandrawsaleandreturn',
            name='raw_sale_and_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawsaleandreturn'),
        ),
        migrations.AddField(
            model_name='ledgerandrawpurchase',
            name='ledger_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_raw_purchase', to='ledgers.ledger'),
        ),
        migrations.AddField(
            model_name='ledgerandrawpurchase',
            name='raw_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawpurchase'),
        ),
    ]
