# Generated by Django 3.2.12 on 2022-03-04 16:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.PositiveBigIntegerField()),
                ('cheque_number', models.CharField(max_length=20)),
                ('bank', models.CharField(choices=[('meezan', 'Meezan Bank'), ('al_baraka', 'Al Baraka Bank'), ('habib_metro', 'Habib Metropolitan Bank'), ('askari', 'Al Baraka Bank'), ('allied', 'Allied Bank'), ('alfalah', 'Bank Alfalah'), ('al_habib', 'Bank Al-Habib'), ('dubai_islami', 'Dubai Bank Islami'), ('citi', 'Citi Bank'), ('islami', 'Bank Islami'), ('faysal', 'Faysal Bank'), ('first_woman', 'First Women Bank'), ('hbl', 'Habib Bank Limited'), ('standard_chartered', 'Standard Chartered Bank'), ('js', 'JS Bank Limited'), ('mcb', 'MCB Bank Limited'), ('mcb_islamic', 'MCB Islamic Bank Limited'), ('national', 'National Bank of Pakistan')], max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred'), ('cleared', 'Cleared'), ('returned', 'Returned')], default='pending', max_length=12)),
                ('is_passed_with_history', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.person')),
            ],
            options={
                'ordering': ['serial', 'due_date'],
                'abstract': False,
                'unique_together': {('bank', 'cheque_number')},
            },
        ),
        migrations.CreateModel(
            name='ExternalChequeTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cheque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cheques.externalcheque')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.person')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalChequeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('date', models.DateField(default=datetime.date.today)),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.accounttype')),
                ('cheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheque_history', to='cheques.externalcheque')),
                ('parent_cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_cheque', to='cheques.externalcheque')),
                ('return_cheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_cheque', to='cheques.externalcheque')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.PositiveBigIntegerField()),
                ('cheque_number', models.CharField(max_length=20)),
                ('bank', models.CharField(choices=[('meezan', 'Meezan Bank'), ('al_baraka', 'Al Baraka Bank'), ('habib_metro', 'Habib Metropolitan Bank'), ('askari', 'Al Baraka Bank'), ('allied', 'Allied Bank'), ('alfalah', 'Bank Alfalah'), ('al_habib', 'Bank Al-Habib'), ('dubai_islami', 'Dubai Bank Islami'), ('citi', 'Citi Bank'), ('islami', 'Bank Islami'), ('faysal', 'Faysal Bank'), ('first_woman', 'First Women Bank'), ('hbl', 'Habib Bank Limited'), ('standard_chartered', 'Standard Chartered Bank'), ('js', 'JS Bank Limited'), ('mcb', 'MCB Bank Limited'), ('mcb_islamic', 'MCB Islamic Bank Limited'), ('national', 'National Bank of Pakistan')], max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.accounttype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.person')),
            ],
            options={
                'ordering': ['serial', 'due_date'],
                'abstract': False,
                'unique_together': {('bank', 'cheque_number')},
            },
        ),
    ]
