# Generated by Django 3.2.11 on 2022-02-08 11:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('essentials', '0010_alter_person_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=255)),
                ('bank', models.CharField(choices=[('meezan', 'Meezan Bank Limited'), ('al_baraka', 'Al Baraka Bank (Pakistan) Limited'), ('habib_metro', 'Habib Metropolitan Bank Limited')], max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('is_passed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChequeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.accounttype')),
                ('cheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque', to='cheques.cheque')),
                ('return_cheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_cheque', to='cheques.cheque')),
            ],
        ),
    ]
