# Generated by Django 3.2.11 on 2022-02-08 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='amount',
            field=models.FloatField(default=50000, validators=[django.core.validators.MinValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
