# Generated by Django 3.2.11 on 2022-02-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_cheque_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='cheque_number',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cheque',
            name='serial',
            field=models.PositiveBigIntegerField(),
        ),
    ]
