# Generated by Django 3.2.11 on 2022-02-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0011_linkedaccount'),
        ('cheques', '0004_cheque_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.person'),
        ),
    ]
