# Generated by Django 3.2.12 on 2022-03-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('cheques', '0004_alter_externalcheque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcheque',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externalcheque', to='authentication.branch'),
        ),
        migrations.AddField(
            model_name='externalchequehistory',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externalchequehistory', to='authentication.branch'),
        ),
        migrations.AddField(
            model_name='externalchequetransfer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externalchequetransfer', to='authentication.branch'),
        ),
        migrations.AddField(
            model_name='personalcheque',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalcheque', to='authentication.branch'),
        ),
    ]
