# Generated by Django 3.2.11 on 2022-02-18 13:33

import datetime
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0005_alter_cheque_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.PositiveBigIntegerField()),
                ('cheque_number', models.CharField(max_length=20)),
                ('bank', models.CharField(choices=[('meezan', 'Meezan Bank Limited'), ('al_baraka', 'Al Baraka Bank (Pakistan) Limited'), ('habib_metro', 'Habib Metropolitan Bank Limited')], max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('is_passed', models.BooleanField(default=False)),
                ('is_returned', models.BooleanField(default=False)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred'), ('completed', 'Completed')], max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalChequeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.PositiveBigIntegerField()),
                ('cheque_number', models.CharField(max_length=20)),
                ('bank', models.CharField(choices=[('meezan', 'Meezan Bank Limited'), ('al_baraka', 'Al Baraka Bank (Pakistan) Limited'), ('habib_metro', 'Habib Metropolitan Bank Limited')], max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('is_passed', models.BooleanField(default=False)),
                ('is_returned', models.BooleanField(default=False)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='person',
        ),
        migrations.RemoveField(
            model_name='chequehistory',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='chequehistory',
            name='cheque',
        ),
        migrations.RemoveField(
            model_name='chequehistory',
            name='return_cheque',
        ),
    ]
