# Generated by Django 3.2.12 on 2022-03-09 15:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_branch_options'),
        ('cheques', '0005_auto_20220309_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalchequehistory',
            options={'verbose_name_plural': 'External cheque history'},
        ),
        migrations.AlterField(
            model_name='externalcheque',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='externalcheque', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='externalchequehistory',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='externalchequehistory', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='externalchequetransfer',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='externalchequetransfer', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='personalcheque',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='personalcheque', to='authentication.branch'),
        ),
    ]
