# Generated by Django 3.2.12 on 2022-03-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_branch_options'),
        ('cheques', '0006_auto_20220309_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcheque',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalcheque', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='externalchequehistory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalchequehistory', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='externalchequetransfer',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalchequetransfer', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='personalcheque',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalcheque', to='authentication.branch'),
        ),
    ]
