# Generated by Django 3.2.11 on 2022-02-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0006_auto_20220218_1833'),
        ('essentials', '0012_branch_userbranchrelation'),
        ('ledgers', '0012_auto_20220218_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cheque',
        ),
        migrations.DeleteModel(
            name='ChequeHistory',
        ),
        migrations.AddField(
            model_name='personalcheque',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.accounttype'),
        ),
        migrations.AddField(
            model_name='personalcheque',
            name='issued_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.person'),
        ),
        migrations.AddField(
            model_name='externalchequehistory',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.accounttype'),
        ),
        migrations.AddField(
            model_name='externalchequehistory',
            name='cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_history', to='cheques.externalcheque'),
        ),
        migrations.AddField(
            model_name='externalchequehistory',
            name='parent_cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_cheque', to='cheques.externalcheque'),
        ),
        migrations.AddField(
            model_name='externalchequehistory',
            name='return_cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_cheque', to='cheques.externalcheque'),
        ),
        migrations.AddField(
            model_name='externalcheque',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.person'),
        ),
    ]
