# Generated by Django 3.2.11 on 2022-02-20 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0012_branch_userbranchrelation'),
        ('cheques', '0007_auto_20220218_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcheque',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred'), ('completed', 'Completed'), ('returned', 'Returned')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='externalchequehistory',
            name='parent_cheque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_cheque', to='cheques.externalcheque'),
        ),
        migrations.AlterUniqueTogether(
            name='externalcheque',
            unique_together={('bank', 'cheque_number')},
        ),
        migrations.AlterUniqueTogether(
            name='personalcheque',
            unique_together={('bank', 'cheque_number')},
        ),
        migrations.CreateModel(
            name='ExternalChequeTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.externalcheque')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essentials.person')),
            ],
        ),
    ]
