# Generated by Django 3.2.12 on 2022-04-15 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheques', '0007_auto_20220309_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcheque',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='externalcheque', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalchequehistory',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='externalchequehistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalchequetransfer',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='externalchequetransfer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalcheque',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personalcheque', to=settings.AUTH_USER_MODEL),
        ),
    ]
