# Generated by Django 3.2.11 on 2022-02-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0008_auto_20220220_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalchequetransfer',
            name='cheque',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cheques.externalcheque'),
        ),
    ]
