# Generated by Django 3.2.12 on 2022-06-02 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0008_auto_20220415_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalchequehistory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='externalchequetransfer',
            name='branch',
        ),
        migrations.AlterField(
            model_name='externalcheque',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='personalcheque',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
