# Generated by Django 3.2.12 on 2022-06-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0010_auto_20220602_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalcheque',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='personalcheque',
            name='branch',
        ),
    ]
