# Generated by Django 3.2.11 on 2022-02-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0010_externalchequehistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalcheque',
            name='is_passed',
        ),
        migrations.RemoveField(
            model_name='externalcheque',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='personalcheque',
            name='is_passed',
        ),
        migrations.RemoveField(
            model_name='personalcheque',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='personalcheque',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('returned', 'Returned')], default='pending', max_length=12),
        ),
    ]
