# Generated by Django 3.2.11 on 2022-02-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0011_auto_20220222_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalcheque',
            old_name='issued_to',
            new_name='person',
        ),
    ]
