# Generated by Django 3.2.12 on 2022-06-05 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0011_auto_20220602_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalchequehistory',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='externalchequehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
