# Generated by Django 3.2.11 on 2022-02-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0012_rename_issued_to_personalcheque_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcheque',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred'), ('cleared', 'Cleared'), ('returned', 'Returned')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='personalcheque',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
