# Generated by Django 3.2.11 on 2022-03-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0013_auto_20220224_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalcheque',
            options={'ordering': ['serial', 'due_date']},
        ),
        migrations.AlterModelOptions(
            name='personalcheque',
            options={'ordering': ['serial', 'due_date']},
        ),
        migrations.AddField(
            model_name='externalcheque',
            name='is_passed_with_history',
            field=models.BooleanField(default=False),
        ),
    ]
