# Generated by Django 3.2.12 on 2022-03-24 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_alter_userbranchrelation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyingIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dying_lot_number', models.PositiveBigIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DyingUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dyingunit', to='authentication.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DyingIssueDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('actual_gazaana', models.FloatField()),
                ('expected_gazaana', models.FloatField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dyingissuedetail', to='authentication.branch')),
                ('dying_lot_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dying.dyingissue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
