# Generated by Django 3.2.12 on 2022-03-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rawtransactions', '0001_initial'),
        ('dying', '0001_initial'),
        ('authentication', '0004_alter_userbranchrelation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyingissuedetail',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rawtransactions.formula'),
        ),
        migrations.AddField(
            model_name='dyingissue',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dyingissue', to='authentication.branch'),
        ),
        migrations.AddField(
            model_name='dyingissue',
            name='dying_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dying.dyingunit'),
        ),
        migrations.AddField(
            model_name='dyingissue',
            name='lot_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawtransactionlot'),
        ),
    ]
