# Generated by Django 3.2.12 on 2022-03-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0012_auto_20220319_2025'),
        ('dying', '0003_alter_dyingunit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyingissuedetail',
            name='warehouse',
            field=models.ForeignKey(default='9ae36ed8-84d7-4b85-a161-fbd0981263d8', on_delete=django.db.models.deletion.PROTECT, to='essentials.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dyingissuedetail',
            name='dying_lot_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dying_issue_details', to='dying.dyingissue'),
        ),
    ]
