# Generated by Django 3.2.12 on 2022-04-15 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dying', '0005_auto_20220331_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyingissue',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dyingissue', to=settings.AUTH_USER_MODEL),
        ),
    ]
