# Generated by Django 3.2.12 on 2022-06-02 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dying', '0006_dyingissue_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyingissue',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='dyingissuedetail',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='dyingissuelot',
            name='branch',
        ),
        migrations.AlterField(
            model_name='dyingissue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
