# Generated by Django 3.2.12 on 2022-08-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dying', '0008_dyingissue_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyingissuelot',
            name='lot_number',
        ),
    ]
