# Generated by Django 3.2.12 on 2022-08-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dying', '0009_remove_dyingissuelot_lot_number'),
        ('rawtransactions', '0021_auto_20220813_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyingissuelot',
            name='purchase_lot_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rawtransactions.rawpurchaselot'),
            preserve_default=False,
        ),
    ]
