# Generated by Django 3.2.12 on 2022-04-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='category',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('cancelled_transaction', 'Cancelled Transaction'), ('expense', 'Expense'), ('ledger_entry', 'Ledger entry'), ('external_cheque', 'External cheque'), ('external_cheque_history', 'External cheque history'), ('personal_cheque', 'External cheque'), ('personal_cheque_history', 'Personal cheque history'), ('stock_transfer', 'Stock transfer'), ('cancelled_stock_transfer', 'Cancelled stock transfer'), ('person', 'Person'), ('account_type', 'Account type'), ('warehouse', 'Warehouse'), ('product', 'Product'), ('product_category', 'Product category'), ('area', 'Area')], max_length=32),
        ),
        migrations.AlterField(
            model_name='log',
            name='detail',
            field=models.CharField(max_length=256),
        ),
    ]
