# Generated by Django 3.2.12 on 2022-06-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20220421_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='time_stamp',
            new_name='date',
        ),
    ]
