# Generated by Django 3.2.12 on 2022-06-02 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_rename_time_stamp_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
