# Generated by Django 3.2.12 on 2022-06-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_log_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date',
        ),
    ]
