# Generated by Django 3.2.12 on 2022-08-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_remove_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='detail',
            field=models.TextField(max_length=1000),
        ),
    ]
