# Generated by Django 3.2.12 on 2022-03-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.IntegerField(default=85572),
            preserve_default=False,
        ),
    ]
