# Generated by Django 3.2.8 on 2021-10-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
