# Generated by Django 3.2.8 on 2022-01-14 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_head', 'product_color')},
        ),
    ]
