# Generated by Django 3.2.8 on 2022-01-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0002_auto_20220114_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthead',
            name='id_ptr',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_head',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductHead',
        ),
    ]
