# Generated by Django 3.2.12 on 2022-03-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0003_alter_area_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='opening_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
