# Generated by Django 3.2.12 on 2022-03-06 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0004_person_opening_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Phone number should look like this (+923001234567)', regex='^\\+\\d{12}$')]),
        ),
    ]
