# Generated by Django 3.2.8 on 2022-01-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0004_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
