# Generated by Django 3.2.11 on 2022-01-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0005_remove_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
