# Generated by Django 3.2.11 on 2022-01-20 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0005_remove_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='yards_per_piece',
            field=models.FloatField(default=44.0, validators=[django.core.validators.MinValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
