# Generated by Django 3.2.12 on 2022-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0005_auto_20220306_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='basic_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='si_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='opening_stock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='opening_stock_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
