# Generated by Django 3.2.11 on 2022-01-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0006_stock_yards_per_piece'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'warehouse', 'yards_per_piece')},
        ),
    ]
