# Generated by Django 3.2.12 on 2022-03-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0006_auto_20220306_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbranchrelation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userbranchrelation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='UserBranchRelation',
        ),
    ]
