# Generated by Django 3.2.11 on 2022-01-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0006_auto_20220116_0247'),
        ('essentials', '0007_alter_stock_unique_together'),
    ]

    operations = [
    ]
