# Generated by Django 3.2.12 on 2022-03-09 15:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_branch_options'),
        ('essentials', '0008_auto_20220309_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='accounttype', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='area',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='area', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='linkedaccount',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='linkedaccount', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='person', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='product', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='authentication.branch'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(default=uuid.UUID('c284e738-28d0-4e0d-8f21-8af9b71e60ea'), on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='authentication.branch'),
        ),
    ]
