# Generated by Django 3.2.12 on 2022-03-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userbranchrelation_role'),
        ('essentials', '0010_auto_20220309_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'warehouse', 'yards_per_piece', 'branch')},
        ),
    ]
