# Generated by Django 3.2.12 on 2022-03-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0011_auto_20220312_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='opening_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='opening_stock_rate',
        ),
        migrations.AddField(
            model_name='stock',
            name='opening_stock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='opening_stock_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
