# Generated by Django 3.2.12 on 2022-04-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userbranchrelation_role'),
        ('essentials', '0012_auto_20220319_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CRK', 'CRK'), ('AK', 'AK'), ('DMD', 'DMD'), ('KS', 'KS')], default='AK', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category', 'branch')},
        ),
    ]
