# Generated by Django 3.2.12 on 2022-04-05 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userbranchrelation_role'),
        ('essentials', '0014_auto_20220405_0546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Categories', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='cb6f38ec-626e-468c-834c-cd03e5488667', on_delete=django.db.models.deletion.PROTECT, to='essentials.productcategory'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'branch')},
        ),
    ]
