# Generated by Django 3.2.12 on 2022-04-07 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0015_auto_20220405_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_rate',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
