# Generated by Django 3.2.12 on 2022-04-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0016_product_minimum_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
    ]
