# Generated by Django 3.2.12 on 2022-04-18 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0017_alter_person_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='yards_per_piece',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
