# Generated by Django 3.2.12 on 2022-06-02 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0018_alter_stock_yards_per_piece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedaccount',
            name='branch',
        ),
        migrations.AlterField(
            model_name='linkedaccount',
            name='name',
            field=models.CharField(choices=[('cheque_account', 'cheque_account')], max_length=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='yards_per_piece',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
    ]
