# Generated by Django 3.2.12 on 2022-06-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0019_auto_20220602_1244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'warehouse', 'yards_per_piece')},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_quantity',
        ),
    ]
