# Generated by Django 3.2.12 on 2022-06-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0020_auto_20220602_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='address',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
    ]
