# Generated by Django 3.2.12 on 2022-06-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0021_auto_20220602_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_rate',
        ),
    ]
