# Generated by Django 3.2.12 on 2022-06-28 22:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userbranchrelation_role'),
        ('essentials', '0022_remove_product_minimum_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningSaleData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('revenue', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('cogs', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('expense', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openingsaledata', to='authentication.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
