# Generated by Django 3.2.12 on 2022-06-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0023_openingsaledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('S', 'Supplier'), ('C', 'Customer'), ('E', 'Equity')], max_length=1),
        ),
    ]
