# Generated by Django 3.2.12 on 2022-06-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0024_alter_person_person_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openingsaledata',
            options={'verbose_name_plural': 'Opening Sales Data'},
        ),
    ]
