# Generated by Django 3.2.12 on 2022-07-08 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userbranchrelation_role'),
        ('essentials', '0026_remove_person_opening_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Phone number should look like this (+923001234567)', regex='^\\+\\d{12}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('branch', 'phone_number')},
        ),
    ]
