CAN_CREATE_PRODUCT = "CAN_CREATE_PRODUCT"
CAN_VIEW_PRODUCTS = "CAN_VIEW_PRODUCTS"
CAN_EDIT_PRODUCT = "CAN_EDIT_PRODUCT"

CAN_CREATE_PERSON = "CAN_CREATE_PERSON"
CAN_VIEW_PERSONS = "CAN_VIEW_PERSONS"
CAN_EDIT_PERSON = "CAN_EDIT_PERSON"
