# ESSENTIALS
CAN_CREATE_PRODUCT = "CAN_CREATE_PRODUCT"
CAN_VIEW_PRODUCTS = "CAN_VIEW_PRODUCTS"
CAN_EDIT_PRODUCT = "CAN_EDIT_PRODUCT"

CAN_CREATE_PERSON = "CAN_CREATE_PERSON"
CAN_VIEW_PERSONS = "CAN_VIEW_PERSONS"
CAN_EDIT_PERSON = "CAN_EDIT_PERSON"

CAN_CREATE_WAREHOUSE = "CAN_CREATE_WAREHOUSE"
CAN_VIEW_WAREHOUSES = "CAN_VIEW_WAREHOUSES"
CAN_EDIT_WAREHOUSE = "CAN_EDIT_WAREHOUSE"

CAN_CREATE_ACCOUNT_TYPE = "CAN_CREATE_ACCOUNT_TYPE"
CAN_VIEW_ACCOUNT_TYPES = "CAN_VIEW_ACCOUNT_TYPES"
CAN_EDIT_ACCOUNT_TYPE = "CAN_EDIT_ACCOUNT_TYPE"

CAN_CREATE_AREA = "CAN_CREATE_AREA"
CAN_VIEW_AREAS = "CAN_VIEW_AREAS"
CAN_EDIT_AREA = "CAN_EDIT_AREA"

CAN_CREATE_PRODUCT_CATEGORY = "CAN_CREATE_PRODUCT_CATEGORY"
CAN_VIEW_PRODUCT_CATEGORIES = "CAN_VIEW_PRODUCT_CATEGORIES"
CAN_EDIT_PRODUCT_CATEGORY = "CAN_EDIT_PRODUCT_CATEGORY"

CAN_VIEW_FULL_DAYBOOK = "CAN_VIEW_FULL_DAYBOOK"
CAN_VIEW_PARTIAL_DAYBOOK = "CAN_VIEW_PARTIAL_DAYBOOK"

CAN_VIEW_ACCOUNT_HISTORY = "CAN_VIEW_ACCOUNT_HISTORY"

CAN_CREATE_OPENING_STOCK = "CAN_CREATE_OPENING_STOCK"

# EXPENSES
CAN_CREATE_EXPENSE_ACCOUNT = "CAN_CREATE_EXPENSE_ACCOUNT"
CAN_VIEW_EXPENSE_ACCOUNTS = "CAN_VIEW_EXPENSE_ACCOUNTS"
CAN_EDIT_EXPENSE_ACCOUNT = "CAN_EDIT_EXPENSE_ACCOUNT"

CAN_CREATE_EXPENSE = "CAN_CREATE_EXPENSE"
CAN_VIEW_EXPENSES = "CAN_VIEW_EXPENSES"
CAN_EDIT_EXPENSE = "CAN_EDIT_EXPENSE"
CAN_DELETE_EXPENSE = "CAN_DELETE_EXPENSE"

# LEDGERS
CAN_VIEW_PARTIAL_LEDGERS = "CAN_VIEW_PARTIAL_LEDGERS"
CAN_VIEW_FULL_LEDGERS = "CAN_VIEW_FULL_LEDGERS"

CAN_CREATE_LEDGER_ENTRY = "CAN_CREATE_LEDGER_ENTRY"
CAN_EDIT_LEDGER_ENTRY = "CAN_EDIT_LEDGER_ENTRY"
CAN_DELETE_LEDGER_ENTRY = "CAN_DELETE_LEDGER_ENTRY"

# PAYMENTS
CAN_CREATE_PAYMENT = "CAN_CREATE_PAYMENT"
CAN_VIEW_PAYMENTS = "CAN_VIEW_PAYMENTS"
CAN_EDIT_PAYMENT = "CAN_EDIT_PAYMENT"
CAN_DELETE_PAYMENT = "CAN_DELETE_PAYMENT"

# TRANSACTIONS
CAN_CREATE_CUSTOMER_TRANSACTION = "CAN_CREATE_CUSTOMER_TRANSACTION"
CAN_CREATE_SUPPLIER_TRANSACTION = "CAN_CREATE_SUPPLIER_TRANSACTION"
CAN_VIEW_PARTIAL_TRANSACTIONS = "CAN_VIEW_PARTIAL_TRANSACTIONS"
CAN_VIEW_FULL_TRANSACTIONS = "CAN_VIEW_FULL_TRANSACTIONS"
CAN_EDIT_CUSTOMER_TRANSACTION = "CAN_EDIT_CUSTOMER_TRANSACTION"
CAN_EDIT_SUPPLIER_TRANSACTION = "CAN_EDIT_SUPPLIER_TRANSACTION"
CAN_DELETE_CUSTOMER_TRANSACTION = "CAN_DELETE_CUSTOMER_TRANSACTION"
CAN_DELETE_SUPPLIER_TRANSACTION = "CAN_DELETE_SUPPLIER_TRANSACTION"

CAN_VIEW_BUSINESS_PERFORMANCE = "CAN_VIEW_BUSINESS_PERFORMANCE"

CAN_VIEW_TRANSFER_STOCK = "CAN_VIEW_TRANSFER_STOCK"
CAN_CREATE_TRANSFER_STOCK = "CAN_CREATE_TRANSFER_STOCK"
CAN_DELETE_TRANSFER_STOCK = "CAN_DELETE_TRANSFER_STOCK"
CAN_EDIT_TRANSFER_STOCK = "CAN_EDIT_TRANSFER_STOCK"

CAN_VIEW_DETAILED_STOCK = "CAN_VIEW_DETAILED_STOCK"

CAN_VIEW_STOCK = "CAN_VIEW_STOCK"

# REPORTS
CAN_VIEW_BALANCE_SHEET = "CAN_VIEW_BALANCE_SHEET"
CAN_VIEW_INCOME_STATEMENT = "CAN_VIEW_INCOME_STATEMENT"

CAN_VIEW_PARTIAL_BALANCES = "CAN_VIEW_PARTIAL_BALANCES"
CAN_VIEW_FULL_BALANCES = "CAN_VIEW_FULL_BALANCES"

CAN_VIEW_LOW_STOCK = "CAN_VIEW_LOW_STOCK"

CAN_VIEW_PRODUCT_PERFORMANCE = "CAN_VIEW_PRODUCT_PERFORMANCE"

CAN_VIEW_REVENUE_BY_PERIOD = "CAN_VIEW_REVENUE_BY_PERIOD"

# LOGS
CAN_VIEW_LOGS = "CAN_VIEW_LOGS"

# ASSETS
CAN_CREATE_ASSET = "CAN_CREATE_ASSET"
CAN_VIEW_ASSETS = "CAN_VIEW_ASSETS"
CAN_EDIT_ASSET = "CAN_EDIT_ASSET"
CAN_DELETE_ASSET = "CAN_DELETE_ASSET"

# CHEQUES
"""EXTERNAL"""
CAN_CREATE_EXTERNAL_CHEQUE = "CAN_CREATE_EXTERNAL_CHEQUE"
CAN_VIEW_EXTERNAL_CHEQUES = "CAN_VIEW_EXTERNAL_CHEQUES"
CAN_DELETE_EXTERNAL_CHEQUE = "CAN_DELETE_EXTERNAL_CHEQUE"

CAN_MANAGE_EXTERNAL_CHEQUE = "CAN_MANAGE_EXTERNAL_CHEQUE"

CAN_DELETE_EXTERNAL_CHEQUE_HISTORY = "CAN_DELETE_EXTERNAL_CHEQUE_HISTORY"

"""PERSONAL"""
CAN_CREATE_PERSONAL_CHEQUE = "CAN_CREATE_PERSONAL_CHEQUE"
CAN_VIEW_PERSONAL_CHEQUES = "CAN_VIEW_PERSONAL_CHEQUES"
CAN_DELETE_PERSONAL_CHEQUE = "CAN_DELETE_PERSONAL_CHEQUE"

CAN_MANAGE_PERSONAL_CHEQUE = "CAN_MANAGE_PERSONAL_CHEQUE"
